name: Shawn's Blog
description: "Shawn's wonder blog about data. More to follow.  "
url: "http://shawnhermans.github.io/"

contact:
  name: Shawn Hermans
  github: shawnhermans
  twitter: shawnhermans
  linkedin: shawnhermans
  quora: Shawn-Hermans
  email: shawnhermans@gmail.com

markdown: redcarpet
pygments: true
