# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Shawn Hermans
name:             Shawn Hermans
#tagline:          'unstructured and denormalized'
#description:      "I like shiny things!"
url:              http://blog.shawnhermans.com
baseurl:          /

author:
  name:           'Shawn Hermans'

paginate:         5

gems:
  - jekyll-sitemap