title: Shawn Hermans
email: shawnhermans@gmail.com
description: >
  Personal blog of Shawn Hermans.
url:              http://blog.shawnhermans.com
github_username:  shawnhermans
theme: minima
markdown: kramdown
permalink: date
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
