# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Drowning in Data
tagline:          'unstructured and denormalized'
description:      "I like finding shiny things in data!"
url:              http://shawnhermans.github.io
baseurl:          /

author:
  name:           'Shawn Hermans'
  url:            https://twitter.com/shawnhermans

paginate:         5
