# Site settings
title: Need a better title
email: shawnhermans@gmail.com
description: "Shawn's Blog.  pretty basic. "
baseurl: "http://shawnhermans.github.io"
url: "http://shawnhermans.github.io"
twitter_username: shawnhermans
github_username:  shawnhermans

# Build settings
markdown: kramdown
permalink: pretty
