# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Drowning in Data
tagline:          'unstructured and denormalized'
description:      "A blog about data and one man's struggle to make sense of it all."
url:              http://shawnhermans.github.io
baseurl:          /

author:
  name:           'Shawn Hermans'
  url:            https://twitter.com/shawnhermans

paginate:         5
