# Site settings
title: Shawn's Blog
email: shawnhermans@gmail.com
description: "Shawn's crazy blog about data"
url: "http://shawnhermans.github.io"
twitter_username: shawnhermans
github_username:  shawnhermans

# Build settings
markdown: kramdown
permalink: pretty
highlighter:    pygments