# Site settings
title: Need a better title
email: shawnhermans@gmail.com
description: "My blog"
url: "http://shawnhermans.github.io"
twitter_username: shawnhermans
github_username:  shawnhermans

# Build settings
markdown: kramdown
permalink: pretty
