# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Drowning in Data
tagline:          'unstructured and denormalized'
description:      "I like finding shiny things in data!"
url:              http://blog.shawnhermans.com
baseurl:          /

author:
  name:           'Shawn Hermans'
  url:            https://twitter.com/shawnhermans

paginate:         5

gems:
  - jekyll-sitemap