title: Shawn Hermans
email: shawnhermans@gmail.com
description: >
  Personal blog of Shawn Hermans.
url:              http://blog.shawnhermans.com
github_username:  shawnhermans

markdown: kramdown
kramdown:
  input: GFM

permalink: pretty